# Generated by Django 2.1.15 on 2019-12-27 19:15

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='_body2_rendered',
            field=models.TextField(default='# Hello World!', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='body2',
            field=markupfield.fields.MarkupField(default='# Hello World!', rendered_field=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='body2_markup_type',
            field=models.CharField(blank=True, choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default=None, max_length=30, null=True),
        ),
    ]
