# Generated by Django 2.1.15 on 2019-12-27 19:20

from django.db import migrations
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191227_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='_body2_rendered',
            new_name='_body_rendered',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='body2_markup_type',
            new_name='body_markup_type',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='body2',
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=markupfield.fields.MarkupField(rendered_field=True),
        ),
    ]
