# Generated by Django 2.1.13 on 2019-11-08 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191108_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='posted',
            new_name='pub_date',
        ),
    ]
